//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetTemperature.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPiService")]
    public interface IPiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPiService/DoWork", ReplyAction="http://tempuri.org/IPiService/DoWorkResponse")]
        void DoWork(double cpuTemp, double cpuFreq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPiServiceChannel : GetTemperature.ServiceReference1.IPiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PiServiceClient : System.ServiceModel.ClientBase<GetTemperature.ServiceReference1.IPiService>, GetTemperature.ServiceReference1.IPiService {
        
        public PiServiceClient() {
        }
        
        public PiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork(double cpuTemp, double cpuFreq) {
            base.Channel.DoWork(cpuTemp, cpuFreq);
        }
    }
}
